version: "3.8"
services:
  neo4j:
    container_name: products-db
    image: neo4j:4.2.1-enterprise
    restart: always
    environment:
      NEO4J_ACCEPT_LICENSE_AGREEMENT: "yes"
      NEO4J_AUTH: none
    ports:
      - 7474:7474
      - 7687:7687
    volumes:
    - $HOME/neo4j/data:/data
    - $HOME/neo4j/import:/import
  node-server:
    container_name: products-server
    build: ./node-server/
    restart: always
    depends_on:
      - neo4j
    environment:
      DATABASE_HOST: neo4j
      DATABASE_URL: bolt://localhost:7687
      NODE_ENV: development
    ports:
      - 4000:4000
  fec:
    container_name: fec
    build: ./FEC/
    restart: always
    depends_on:
      - node-server
    environment:
      NODE_ENV: development
      SERVER_IP: localhost
    ports:
      - 3000:3000
